uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/AutoRebalanceLiveInstanceChangeListener.java

There is potential dead lock with synchronized.

Remove synchronized on onLiveInstanceChange

---

uReplicator-Worker/src/main/scala/kafka/mirrormaker/KafkaConnector.scala
uReplicator-Worker/src/main/scala/kafka/mirrormaker/MirrorMakerWorker.scala

fix license header

---

pom.xml
uReplicator-Controller/pom.xml
uReplicator-Distribution/pom.xml
uReplicator-Worker/pom.xml

This reverts commit 44a62e54b8d06905b304dab145b7bbff654cca27.

Revert "release version 1.0.0"

---

uReplicator-Worker/src/main/scala/kafka/mirrormaker/HelixWorkerOnlineOfflineStateModelFactory.scala
uReplicator-Worker/src/main/scala/kafka/mirrormaker/KafkaConnector.scala

Fix duplication traffic after worker network partition

---

pom.xml
uReplicator-Controller/pom.xml
uReplicator-Distribution/pom.xml
uReplicator-Distribution/src/main/java/com/uber/stream/kafka/mirrormaker/starter/MirrorMakerStarter.java
uReplicator-Worker/pom.xml
uReplicator-Worker/src/main/scala/kafka/mirrormaker/MirrorMakerWorker.scala
uReplicator-Worker/src/main/scala/kafka/mirrormaker/MirrorMakerWorkerConf.scala

Support extends MirrorMakerWorker

---

uReplicator-Worker/src/main/scala/kafka/mirrormaker/MirrorMakerWorker.scala

Fix #34 
Once entering: https://github.com/apache/helix/blob/helix-0.6.8/helix-core/src/main/java/org/apache/helix/manager/zk/ZKHelixManager.java#L815, we need to shutdown worker otherwise it will keep running without connecting to helix zookeeper.

Fix flapping network issue

---

uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/OffsetMonitor.java

Report the number of lagging partitions that have no progress with commit offset for some time so that it can be used as a single metric to trigger alert.

Report number of lagging partitions that have no progress

---

uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/IdealStateBuilder.java

When a topic is expanded, the new partitions should not be assigned to the same worker. Instead, we assign them to as many workers as possible so that it would not overwhelm a single worker.

Avoid to assign new partitions to the same worker

---

uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/AutoRebalanceLiveInstanceChangeListener.java
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/HelixMirrorMakerManager.java
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/InstanceTopicPartitionHolder.java
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/rest/resources/MirrorMakerManagerRestletResource.java
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/utils/HelixUtils.java

Use Rest API to blacklist a specific worker in workload assignment:
curl -X DELETE localhost:$port/instances/$instanceName
And whitelist a worker back:
curl -X POST localhost:$port/instances/$instanceName

Blacklist specific workers

---

Dockerfile
docker-entrypoint.sh

Add license in Dockerfile

---

pom.xml
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/reporter/HelixKafkaMirrorMakerMetricsReporter.java

3.1 is EOL.
Add jmx dependency.

Bump dropwizard metrics version

---

pom.xml
uReplicator-Common/src/main/java/com/uber/stream/kafka/mirrormaker/common/utils/HelixUtils.java
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/HelixMirrorMakerManager.java
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/ManagerControllerHelix.java
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/OffsetMonitor.java
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/rest/resources/MirrorMakerManagerRestletResource.java
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/validation/ValidationManager.java
uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/ManagerConf.java
uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/ManagerStarter.java
uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/core/ControllerHelixManager.java
uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/core/ControllerLiveInstanceChangeListener.java
uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/core/IdealStateBuilder.java
uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/core/WorkerHelixManager.java
uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/reporter/HelixKafkaMirrorMakerMetricsReporter.java
uReplicator-Manager/src/test/java/com/uber/stream/kafka/mirrormaker/manager/rest/TestManagerTopicManagement.java
uReplicator-Worker/src/main/scala/kafka/mirrormaker/ManagerWorkerHelixHandler.scala
uReplicator-Worker/src/main/scala/kafka/mirrormaker/MirrorMakerWorker.scala
uReplicator-Worker/src/main/scala/kafka/mirrormaker/WorkerInstance.scala

1. Fix controller offline when route is not established
2. Fix manager auto-balance when config is changed

Fix controller offline logic and manager auto-balance config

---

uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/core/ControllerHelixManager.java
uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/core/WorkerHelixManager.java

Manager might failed to create idealstate for one route between manager and worker while succeed between manager and controller. So manager need to check if idealstate exists before adding more workers into one route.

Fix adding worker logic and update status interval

---

uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/rest/resources/TopicManagementRestletResource.java

Return 200 when deleting non-exist topic so caller won't delete it again.

Return 200 when deleting non-exist topic

---

pom.xml

Fix https://issues.apache.org/jira/browse/ZOOKEEPER-706.
If manager/controller has a huge watch list, zookeeper will force close the session.

Upgrade to zookeeper@3.4.9

---

config/producer.properties

Fix compression config to compression.type

---

uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/OffsetMonitor.java
uReplicator-Manager/src/main/java/com/uber/stream/kafka/mirrormaker/manager/core/ControllerHelixManager.java

Improve logging level of some critical info so we can filter in ELK in future

raise logging level of validation wrong and no-progress

---

uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/core/KafkaBrokerTopicObserver.java

fix topic auto expand bug, topic partition mointor schduler refresh intervel set too long

---

devenv/Dockerfile

Fix broken devenv docker base image/Kafka download URL

---

uReplicator-Common/src/main/java/com/uber/stream/ureplicator/common/KafkaClusterObserver.java
uReplicator-Common/src/main/java/com/uber/stream/ureplicator/common/KafkaUReplicatorMetricsReporter.java
uReplicator-Controller/src/main/java/com/uber/stream/kafka/mirrormaker/controller/ControllerInstance.java
uReplicator-Manager/src/test/java/com/uber/stream/kafka/mirrormaker/manager/rest/TestManagerTopicManagement.java
uReplicator-Worker-3.0/src/main/java/com/uber/stream/ureplicator/worker/ConsumerFetcherThread.java
uReplicator-Worker-3.0/src/main/java/com/uber/stream/ureplicator/worker/FetcherManager.java
uReplicator-Worker-3.0/src/main/java/com/uber/stream/ureplicator/worker/ProducerThread.java
uReplicator-Worker-3.0/src/main/java/com/uber/stream/ureplicator/worker/WorkerInstance.java
uReplicator-Worker-3.0/src/main/java/com/uber/stream/ureplicator/worker/WorkerStarter.java
uReplicator-Worker-3.0/src/main/java/com/uber/stream/ureplicator/worker/ZookeeperCheckpointManager.java
uReplicator-Worker-3.0/src/main/java/com/uber/stream/ureplicator/worker/helix/ControllerWorkerHelixHandler.java
uReplicator-Worker-3.0/src/main/java/com/uber/stream/ureplicator/worker/helix/ManagerWorkerHelixHandler.java
uReplicator-Worker-3.0/src/main/java/com/uber/stream/ureplicator/worker/interfaces/ICheckPointManager.java
uReplicator-Worker-3.0/src/test/java/com/uber/stream/ureplicator/worker/FetcherManagerTest.java
uReplicator-Worker-3.0/src/test/java/com/uber/stream/ureplicator/worker/HelixHandlerTest.java
uReplicator-Worker-3.0/src/test/java/com/uber/stream/ureplicator/worker/TestUtils.java
uReplicator-Worker-3.0/src/test/java/com/uber/stream/ureplicator/worker/WorkerInstanceTest.java
uReplicator-Worker-3.0/src/test/java/com/uber/stream/ureplicator/worker/ZookeeperCheckpointManagerTest.java
uReplicator-Worker-3.0/src/test/resources/clusters.properties

1.    parallel commit offset
2.    fix worker failed to commit offset problem for federated mode on route re-assign
3.    refactor on worker federated mode
3.1. throw exception on unexpected behaviour
3.2. add more check to avoid potential race condition
3.3. add unit test for error scenarios
4. not to shutdown fetcher thread when the assignment is empty

Refactor and bug fix for uReplicator Worker

---

config/consumer.properties
pom.xml

1. fix jetty namespace collision
2. fix configuration for quickstart

fix namespace collision and quickstart configuration
